spring.application.name=engineeringDeptComplaintApp
# PostgreSQL database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/db_engDept_complaint
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect